//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace COFFEE.Module.BusinessObjects.COFFEE
{

    [DefaultProperty("SoBan")]
    public partial class HOADON : DevExpress.Persistent.BaseImpl.BaseObject
    {
        string fKhachID;
        public string KhachID
        {
            get { return fKhachID; }
            set { SetPropertyValue<string>(nameof(KhachID), ref fKhachID, value); }
        }
        string fNhanVienID;
        public string NhanVienID
        {
            get { return fNhanVienID; }
            set { SetPropertyValue<string>(nameof(NhanVienID), ref fNhanVienID, value); }
        }
        int fSoBan;
        public int SoBan
        {
            get { return fSoBan; }
            set { SetPropertyValue<int>(nameof(SoBan), ref fSoBan, value); }
        }
        DateTime fNgay;
        [DevExpress.ExpressApp.Model.ModelDefault("EditMask", "dd/MM/yyyy HH:mm"),
DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat", "{0:dd/MM/yyyy HH:mm}")]
        public DateTime Ngay
        {
            get { return fNgay; }
            set { SetPropertyValue<DateTime>(nameof(Ngay), ref fNgay, value); }
        }
        [Association(@"HOADONCTReferencesHOADON"), Aggregated]
        public XPCollection<HOADONCT> HOADONCTs { get { return GetCollection<HOADONCT>(nameof(HOADONCTs)); } }
    }

}
