//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace COFFEE.Module.BusinessObjects.COFFEE
{

    public partial class HOADONCT : DevExpress.Persistent.BaseImpl.BaseObject
    {
        HOADON fHoaDonID;
        [Association(@"HOADONCTReferencesHOADON")]
        public HOADON HoaDonID
        {
            get { return fHoaDonID; }
            set { SetPropertyValue<HOADON>(nameof(HoaDonID), ref fHoaDonID, value); }
        }
        SANPHAM fSanPhamID;
        [Association(@"HOADONCTReferencesSANPHAM")]
        public SANPHAM SanPhamID
        {
            get { return fSanPhamID; }
            set { SetPropertyValue<SANPHAM>(nameof(SanPhamID), ref fSanPhamID, value); }
        }
        double fSoLuong;
        public double SoLuong
        {
            get { return fSoLuong; }
            set { SetPropertyValue<double>(nameof(SoLuong), ref fSoLuong, value); }
        }
        decimal fDonGia;
        public decimal DonGia
        {
            get { return fDonGia; }
            set { SetPropertyValue<decimal>(nameof(DonGia), ref fDonGia, value); }
        }
        [PersistentAlias("ToDecimal([SoLuong]) * [DonGia]")]
        public string ThanhTien
        {
            get { return (string)(EvaluateAlias(nameof(ThanhTien))); }
        }
    }

}
