//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace COFFEE.Module.BusinessObjects.COFFEE
{

    public partial class KHACHHANG : DevExpress.Persistent.BaseImpl.BaseObject
    {
        string fHoTen;
        public string HoTen
        {
            get { return fHoTen; }
            set { SetPropertyValue<string>(nameof(HoTen), ref fHoTen, value); }
        }
        string fDienThoai;
        public string DienThoai
        {
            get { return fDienThoai; }
            set { SetPropertyValue<string>(nameof(DienThoai), ref fDienThoai, value); }
        }
        string fMST;
        public string MST
        {
            get { return fMST; }
            set { SetPropertyValue<string>(nameof(MST), ref fMST, value); }
        }
    }

}
