//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace COFFEE.Module.BusinessObjects.COFFEE
{

    [DefaultProperty("TenSP")]
    public partial class SANPHAM : DevExpress.Persistent.BaseImpl.BaseObject
    {
        string fNhomID;
        public string NhomID
        {
            get { return fNhomID; }
            set { SetPropertyValue<string>(nameof(NhomID), ref fNhomID, value); }
        }
        string fTenSP;
        [Size(30)]
        public string TenSP
        {
            get { return fTenSP; }
            set { SetPropertyValue<string>(nameof(TenSP), ref fTenSP, value); }
        }
        string fDVT;
        [Size(10)]
        public string DVT
        {
            get { return fDVT; }
            set { SetPropertyValue<string>(nameof(DVT), ref fDVT, value); }
        }
        decimal fGiaBan;
        [DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat", "### ### ### ###"),
DevExpress.ExpressApp.Model.ModelDefault("EditMask", "### ### ### ###")]
        public decimal GiaBan
        {
            get { return fGiaBan; }
            set { SetPropertyValue<decimal>(nameof(GiaBan), ref fGiaBan, value); }
        }
        [Association(@"HOADONCTReferencesSANPHAM"), Aggregated]
        public XPCollection<HOADONCT> HOADONCTs { get { return GetCollection<HOADONCT>(nameof(HOADONCTs)); } }
    }

}
